/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as TurnoTokenRouteImport } from './routes/turno.$token'
import { Route as PanelClientesIndexRouteImport } from './routes/panel/clientes/index'
import { Route as PanelClientesIdRouteImport } from './routes/panel/clientes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnoTokenRoute = TurnoTokenRouteImport.update({
  id: '/turno/$token',
  path: '/turno/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelClientesIndexRoute = PanelClientesIndexRouteImport.update({
  id: '/panel/clientes/',
  path: '/panel/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelClientesIdRoute = PanelClientesIdRouteImport.update({
  id: '/panel/clientes/$id',
  path: '/panel/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/clientes/$id': typeof PanelClientesIdRoute
  '/panel/clientes/': typeof PanelClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/panel': typeof PanelIndexRoute
  '/panel/clientes/$id': typeof PanelClientesIdRoute
  '/panel/clientes': typeof PanelClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/clientes/$id': typeof PanelClientesIdRoute
  '/panel/clientes/': typeof PanelClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reservar'
    | '/turno/$token'
    | '/panel/'
    | '/panel/clientes/$id'
    | '/panel/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reservar'
    | '/turno/$token'
    | '/panel'
    | '/panel/clientes/$id'
    | '/panel/clientes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reservar'
    | '/turno/$token'
    | '/panel/'
    | '/panel/clientes/$id'
    | '/panel/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ReservarRoute: typeof ReservarRoute
  TurnoTokenRoute: typeof TurnoTokenRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelClientesIdRoute: typeof PanelClientesIdRoute
  PanelClientesIndexRoute: typeof PanelClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turno/$token': {
      id: '/turno/$token'
      path: '/turno/$token'
      fullPath: '/turno/$token'
      preLoaderRoute: typeof TurnoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/clientes/': {
      id: '/panel/clientes/'
      path: '/panel/clientes'
      fullPath: '/panel/clientes/'
      preLoaderRoute: typeof PanelClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/clientes/$id': {
      id: '/panel/clientes/$id'
      path: '/panel/clientes/$id'
      fullPath: '/panel/clientes/$id'
      preLoaderRoute: typeof PanelClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ReservarRoute: ReservarRoute,
  TurnoTokenRoute: TurnoTokenRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelClientesIdRoute: PanelClientesIdRoute,
  PanelClientesIndexRoute: PanelClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
